server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sachin
    username: sachin
    password: sachin
  jpa:
    properties:
      ddl-auto: update
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true