spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
logging:
  level:
    root: INFO
    com.ecommerce.user1: TRACE
  file:
    name: log/${spring.application.name}.log
  rollingpolicy:
    max-file-size: 5MB
    max-history: 7

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#
#    instance:
#      ip-address: 127.0.0.1
#      prefer-ip-address: true
#

