spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
logging:
  level:
    org.springframework.cloud.config: DEBUG

